### PR TITLE
Port to `boost/core/snprintf.hpp`

### PR DESCRIPTION
**Pull request by Lastique**
This replaces `snprintf`/`swprintf` workarounds with the more portable definitions in Boost.Core. This fixes compilation errors on MinGW32 introduced in a142dfecda7644e58382f4b6c527f37309af03f4.

Also converted a few tabs to spaces.

### CODE REVIEW

**Comment by jzmaddock** [comment]
I've handled this slightly differently in https://github.com/boostorg/regex/pull/189 in order to maintain standalone mode, let me know if I've missed anything.
